### ISSUE TITLE
New fields: Private adress and e-mail adress in "personal data" tab

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_memberlist#13]
We need to add new fields in the backend and frontend. Under "Personal Data" the user should be able to add his personal postal address and e-mail address.

We need the fields:
- street and number
- zip code
- Place

- private e-mail address

The user shall be able to add them on the registration page and also he shall be able to edit them on the page where he can edit his profile. And ultimately the data shall appear in the backend under the tab "Personal Data" if possible.

**Comment by nitsan-technologies** [comment]
Hi @michelrossier  ,

Please check it now: BE: http://prntscr.com/ce9nna , FE: http://prntscr.com/ce9nxl

Thank you!

**Comment by michelrossier** [comment]
Perfect, that works.
