### ISSUE TITLE
Forms: List of countries

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_memberlist#14]
Regarding the dropdown of countries in the registration form and my membership page form. Is there a way to display them simplified? Currently it says for each country like "Republic of Poland" or "Swiss Confederation" but it should just say "Poland" or "Switzerland". And is it possible to have Switzerland on top of the list? Because 99% of registrants will come from Switzerland.

**Comment by nitsan-technologies** [comment]
Hi @michelrossier 

As per our call discussion, you wil talk with Angelo by Monday & will write back to us here.
Thanks!

**Comment by michelrossier** [comment]
Hi @nitsan-technologies 
I discussed this with Angelo and we installed "Static Info Tables (de)" and "Static Info Tables (fr)", so the names are now translated correctly. But it still doesn't  work. Can you take it from here?

What we need is an output in this form:
Schweiz
Deutschland 
Liechtenstein
Österreich
Frankreich
Italien 

and the corresponding translations.

By the way, we will duplicate our current development site to dev.sgrm.netconsult.ch Can you please make your development and tests on that domain? So we can be sure that there are no other factors that could skew the results.

I will duplicate the site there within the next 2.5 hours and write you a mail with the infos. You have the access already. Thanks.

**Comment by michelrossier** [comment]
Angelo created a new ticket here for this issue: https://github.com/NetConsultAG/netc_memberlist/issues/21
