### ISSUE TITLE
Hardcoded uid

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_memberlist#15]
There is a hardcoded UID in 
netc_memberlist\Resources\Private\Templates\User\List.html
on line 39.

Took me a while to figure that out, as it caused the form not to work.

**Comment by hitesh-nitsan** [comment]
Hi @michelrossier 

Please check it now > http://prnt.sc/cnb4ee

**Comment by michelrossier** [comment]
This is okay, thanks!
