### ISSUE TITLE
Accounting group: Filter members based on sent or paid bill

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_memberlist#16]
There is an issue with the filtering function for the accounting group members, who have to be able to send a message to the people regarding the bills.

https://i.imgur.com/pX6u1zQ.png

The implementation of #3.4 in the specification document from Angelo is not exactly as expected. 

**The goal:**
**The accountinggroup member has to be able to filter the list to send a message also to the people **who received a bill, but did not pay yet**.**

With the current implementation this scenario is not possible. Angelo mentioned the "YES or NO" functionality. Currently there is only a "YES" option. The "no" option is not implemented.

Can you implement this YES or NO option fields (please do not use radio buttons) that uses AND operators, so that the filtered list shows only members who fullfill every single activated option field? And it should be possible to leave certain years totally unchecked (for example: show me the users that paid the bill in 2015 and not did not pay in 2016, but ignore everything about any other years e.g. 2014 etc.).

If you have a better idea to implement this, let me know.

I hope I could clearly explain the issue, please let me know if you have any questions.

**Comment by nitsan-technologies** [comment]
Hi @michelrossier 

As per our call discussion, We will go with these checkbox:

1. bill send (where bill="sent")
2. paid (where bill="paid")
3. bill send but not paid (where bill="sent" & payment="not_paid")

...

Let us know if any change on this. Thanks!

**Comment by michelrossier** [comment]
Yes, this is okay, you can implement it that way. Thanks.

**Comment by hitesh-nitsan** [comment]
Hi @michelrossier 

We have set another check there who received a bill, but did not pay yet.

FE- http://prntscr.com/cnbjrf 
BE- http://prntscr.com/cnbk69

Let us know your input now! Thanks!

**Comment by michelrossier** [comment]
That works, thank you.
