### ISSUE TITLE
groupname cannot be localized

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_memberlist#17]
In the listview in the backend the elements of the groupnames cannot be localized currently. Can you make that this is possible to translate? 

https://i.imgur.com/oz1SssQ.png

**Comment by nitsan-technologies** [comment]
Hi @michelrossier

As per our call discussion, you will try to add another language user-group & will share with us if any problem with our extension. Thanks!

**Comment by michelrossier** [comment]
Hi @nitsan-technologies we couldn't find a solution to translate the groupnames. As per Angelos research this probably has to be done programmatically by the third party plugin (memberlist). It shouldn't be that the translated group has a different ID, there should be a solution that the group-id stays the same in the different languages.

**Comment by hitesh-nitsan** [comment]
Hi @michelrossier 

We have done this task. Find detail update here:

You have to add the label in netc_memberlist/Resources/Private/Language/locallang.xlf and netc_memberlist/Resources/Private/Language/fr.locallang.xlf files with below syntax:

locallang.xlf:
<trans-unit id="usergroup.{group-uid}">
    <source>{group title}</source>
</trans-unit>

fr.locallang.xlf:
<trans-unit id="usergroup.{group-uid}">
    <target>{group title}</target>
</trans-unit>

The usergroups which have entries in locallang files will have title from the files and the groups which have no entries in locallang files will have title from the database.

locallang files can be managable from backend with lfeditor which we have installed already.

and you can also manage these labels from typoscript with the following syntax

DE:
plugin.tx_netcmemberlist._LOCAL_LANG.default.usergroup.{group-id} = {group title}

FR:
plugin.tx_netcmemberlist._LOCAL_LANG.fr.usergroup.{group-id} = {group title}

Currently we have translated all usergroups
> http://prntscr.com/cn8c11

...

More screenshots:

Frontend: http://prntscr.com/cnqtzd , http://prntscr.com/cnqudw
Backend: http://prntscr.com/cnquxg , http://prntscr.com/cnquq7 , http://prntscr.com/cnqvlc

...

Please share your input on this! Thanks!

**Comment by michelrossier** [comment]
That seems to work fine, thank you!
