### ISSUE TITLE
"One or more attachement"

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_memberlist#18]
I see in the specifications in number 2.7 and  number 3.5 that it is specified that the users can send "one or more attachments". Currently I see in the extension only the option for one attachment. Was this requirement changed? I have not talked with Angelo about that.

**Comment by michelrossier** [comment]
I have this discussed with Angelo, this has to done.

**Comment by hitesh-nitsan** [comment]
Okay. @michelrossier 

This is alredy done ;)

Single - http://prntscr.com/cnc83y
Multiple - http://prntscr.com/cnc8s9 , http://prntscr.com/cnc8zf

**Comment by michelrossier** [comment]
This is okay, thanks!
