### ISSUE TITLE
Texts not translatable

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_memberlist#19]
Hi

These texts don't seem to be translatable:
https://i.imgur.com/2xyxgXa.png

Can you show me how I can translate them or make it translatable? Thanks.

**Comment by hitesh-nitsan** [comment]
Hi @michelrossier 

Please check it now > http://prnt.sc/cncbgi

Thanks!

**Comment by michelrossier** [comment]
This is okay.
