### ISSUE TITLE
In members area: Missing attachement causes error

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_memberlist#2]
In the members area, when a user is logged in: If a user does not attach an attachement to a message to other users, there appears a system error. Please make it possible that the user is not required to add an attachment.

**Comment by nitsan-technologies** [comment]
Hi @michelrossier 

Please check it now > http://prntscr.com/cdn9yb , http://prntscr.com/cdnaxb

Thank you!

**Comment by michelrossier** [comment]
That works, thank you.
