### ISSUE TITLE
Relations Kantone (regions) from old to new website for import of feuser

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_memberlist#20]
![old-cantons](https://cloud.githubusercontent.com/assets/17588253/18835756/089ac63c-83fd-11e6-8eef-91bca7a26df2.jpg)
- uninstall static_info_tables
- use customized field from the EXT:netc_memberlist for cantons (regions).
- Must be modified on BE and FE 

**Cantons old sgrm.ch webseite | Must be on the new website dev.sgrm.netconsult.ch | French translation**

AG = Aargau | Argovie
AI = Appenzell Innerrhoden | Appenzell Rh.-Int.
AR = Appenzell Ausserrhoden | Appenzell Rh.-Ext.
BE = Bern | Berne
BL = Basel-Landschaft | Bâle-Campagne
BS = Basel-Stadt | Bâle-Ville
FR = Freiburg | Fribourg
GE = Genf | Genève
GL = Glarus | Glaris
GR = Graubünden | Grisons
JU = Jura | Jura
LU = Luzern | Lucerne
NE = Neuenburg | Neuchâtel
NW = Nidwalden | Nidwald
OW = Obwalden | Obwald
SG = Sankt Gallen | Saint-Gall
SH = Schaffhausen | Schaffhouse
SO = Solothurn | Soleure
SZ = Schwyz | Schwytz
TG = Thurgau | Thurgovie
TI = Tessin | Tessin
UR = Uri | Uri
VD = Waadt | Vaud
VS = Wallis | Valais
ZG = Zug | Zoug
ZH = Zürich | Zurich

**Comment by hitesh-nitsan** [comment]
Hi @angeloprevitali 

We have done this task. Please check it from you end now:

**Frontend:** http://prntscr.com/cogy5n
**BE Old:** http://prntscr.com/cogyr2

Thanks!

**Comment by michelrossier** [comment]
This is okay, thanks!
