### ISSUE TITLE
Relations Land (countries) from old to new website for import of feuser

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_memberlist#21]
![old-countries](https://cloud.githubusercontent.com/assets/17588253/18835804/497e5dc6-83fd-11e6-8251-e07de1c8683a.jpg)

Description country on old website | Description on NEW website | French translation

CH | Schweiz | Suisse
D | Deutschland | Allemande
A | Österreich | Autriche
FL | Fürstentum Lichtenstein | Principauté de Liechtenstein
FR | Frankreich | France
IT | Italien | Italie

**Comment by michelrossier** [comment]
This is okay, thanks!
