### ISSUE TITLE
Frontend Validation only marks the last 3 required fields

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_memberlist#22]
Hi @nitsan-technologies 

I just noticed that whenever the HTML5 validation doesn't work, then the frontend validation only marks the last 3 required fields as red, but the others are not marked at all:

See in this short video:
https://vimeo.com/185316470

Can you make sure that the validation works for the whole document from top to bottom?

Thanks.

**ADDITION:**

I just noticed that e-mail addresses are not validated. I entered a string lke "sdfsf" into the e-mail address field and the system did not complain. Please make sure that e-mail addresses are checked before submission. Thanks.

**Comment by hitesh-nitsan** [comment]
Hi @michelrossier 

Find our update here:

1. I just noticed that whenever the HTML5 validation doesn't work, then the frontend validation only marks the last 3 required fields as red, but the others are not marked at all:
See in this short video: https://vimeo.com/185316470
Can you make sure that the validation works for the whole document from top to bottom?
**Status: Done**
Screenshot: http://awesomescreenshot.com/01b65c1105

ADDITION:
2. I just noticed that e-mail addresses are not validated. I entered a string lke "sdfsf" into the e-mail address field and the system did not complain. Please make sure that e-mail addresses are checked before submission.
**Status: Done**
Screenshot: http://awesomescreenshot.com/0bf65c1p07

...

Looking forward to your reply here. Thanks!

**Comment by michelrossier** [comment]
This is okay, thanks!
