### ISSUE TITLE
Male/Female is not saved when registering a new user

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_memberlist#23]
When registering a new user here...
http://dev.sgrm.netconsult.ch/de/allgemein/mitgliedschaft/mitgliedschaft-beantragen/

....and chosing **female** (under "Geschlecht " in the billing address), it doesn't store it correctly in the database:
https://i.imgur.com/krjNmC2.png

I've chosen female (weiblich), but it still shows male (männlich) in den tab "Rechnung" of the user.

Can you make sure that the choice of the user is stored and displayed correctly?

**Comment by hitesh-nitsan** [comment]
hi @michelrossier 

Please check it now. Find screenshot & video here:

FE: http://prntscr.com/ct7qhq , http://prntscr.com/ct7qol
BE: http://prntscr.com/ct7pm8 , http://prntscr.com/ct7pp5
Video File: http://recordit.co/UIQCsKyX2l 

_Note: Latest work is at development server. ;)_

Thanks!

**Comment by michelrossier** [comment]
Hi Hitesh

Thanks, that looks very good.

Okay, can you tell me which files did change? So I know which files I have to replace in the live environment. I can not just copy paste the whole extension as we made changes to template etc.

Best regards,
Michel

**Comment by michelrossier** [comment]
This works, thank you!
