### ISSUE TITLE
Name not defined 

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_memberlist#24]
[Backend] In the first tab of the user entry in the database, there is **no "Name" defined**. For the imported user the filed "Name" is consisting of Firstname and Lastname.

Example:
In the imported user entries the field "Name" has an entry:
https://i.imgur.com/CIyBVw9.png

But in any newly created user this field is empty:
https://i.imgur.com/6YEjgFP.png

**Comment by hitesh-nitsan** [comment]
Hi @michelrossier @angeloprevitali 

Please check it now > http://prntscr.com/cy8gm6 , http://prntscr.com/cy8hx9

Thanks!

**Comment by michelrossier** [comment]
This works, thank you!
