### ISSUE TITLE
Import of feuser into dev plattform is not complete!

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_memberlist#25]
The import of the existing feuser of the old website sgrm.ch seems to be completed but all e-mail addresses seems to be NOT imported yet. 

Possible existing e-mail addresses which are found on the dev plattform can be overwritten.

Can you please import those, too and double check if the import is completely done?

Thank you very much for your work and feedback over GitHub.

**Comment by hitesh-nitsan** [comment]
Hi @angeloprevitali @michelrossier 

Well, First of all, This ticket will not consider as bug/issue from NITSAN end. ;)

Michel has already told us to set his email address in to each email field for all records. So he can test it & conifrm it. Please talk with Michel about for more detail.

Now, Do you want to correct/existing email address at development server? 

If yes, then please let us know. Thanks!

**Comment by angeloprevitali** [comment]
Hello 

Yes, please correct the email addresses at developement server.

Thanks.

Best regards,
Angelo

**Comment by hitesh-nitsan** [comment]
Ok. Thanks for your confirmation.

**Comment by hitesh-nitsan** [comment]
Hi @michelrossier @angeloprevitali 

We have imported the email fields. Please check screenshots here:

Dev: http://prntscr.com/cykw42 , Old: http://prntscr.com/cykw8r
Dev: http://prntscr.com/cykwgl , Old: http://prntscr.com/cykwjg
Dev: http://prntscr.com/cykwqt , Old: http://prntscr.com/cykwtd

Thanks!

**Comment by michelrossier** [comment]
Hi @hitesh-nitsan 
Just to make this issue clear: I communicated clearly from the beginning that the e-mail address replacement has to be reveresed at the end, this was part of our agreement the moment I gave you the task, see here:

https://i.imgur.com/K2k0Ai0.png

You confirmed that you will think about a solution, but I have **never** heard back anything negative that this could not work or that it would be an extra work on your side, that would cost more.

This procedure was defenitely required, else it would not have been possible for us to test the sending mechanisms. We cannot send many test mails to the real users.

How do we handle this situation?

**Comment by hitesh-nitsan** [comment]
Hi @michelrossier 

Yes man! Don't take it wrong & don't worry we will not cosider this as extra work. 

As per our Skype discussion, we have find idea to store live email data to another field & added your email id as email records. So you can test it easily with any record as you require.

About situation, Sorry, I didn't got you. We have already made changes at email fields. So now, what do you require?

Thanks!
