### ISSUE TITLE
Input field for Place in tab "Rechnung" is missing

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_memberlist#26]
[Backend] In the third tab of the FE user administration:
https://i.imgur.com/0nEiCpq.png

the input field for "Place" is missing.

In the registry form it is present:
https://i.imgur.com/yyA6i6D.png

But in the backend the value is not displayed. Please make sure that this value is displayed in the backend as well.

**Comment by hitesh-nitsan** [comment]
Hi @michelrossier @angeloprevitali 

Please check it now > http://prnt.sc/cy92rk

Thanks!

**Comment by michelrossier** [comment]
Thanks, that works.
