### ISSUE TITLE
Frontend: Country and Canton is displayed as number

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_memberlist#27]
In the frontend detail view of a user, the canton and country is displayed as a number:
https://i.imgur.com/ejaKFSP.png

Please make sure that here the name is displayed and not the id.

Please have also test if the output of the fields is correct in general.

Thank you.

**Comment by hitesh-nitsan** [comment]
Hi @angeloprevitali @michelrossier 

Please check it now > http://prntscr.com/cy8z02 , http://prntscr.com/cy8zqr

Thanks!

**Comment by michelrossier** [comment]
Thanks, that works.
