### ISSUE TITLE
Groups not displayed translated 

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_memberlist#28]
In several parts of the website the translated group names are not displayed translated:

For example:
On the member overview list page, the page is in french, but the group names appear in german:
https://i.imgur.com/1MkRWeY.png

Also on the page where members can send a message, the list of group names appears in german:
https://i.imgur.com/BexT3vQ.png

Please make sure that the list of group names is displayed in the correct language everywhere.

**Comment by hitesh-nitsan** [comment]
Hi @michelrossier @angeloprevitali 

Please check it now > http://prntscr.com/cy8njx , http://prntscr.com/cy916y

Thanks!

**Comment by michelrossier** [comment]
Thanks, that works.
