### ISSUE TITLE
Where does the "send message" id need to be defined?

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_memberlist#29]
After installing the latest update in our development environment, the **accounting user** cannot click on the link to send a mail to the selected users:

https://i.imgur.com/cXlGjNR.png

If you click on that link, it goes to the homepage. But it should go to the message form, where a message can be send to the selected users. I see in the template that there is a varualble defined: pageUid="{mailPage}" but where is this variable defined?

**Comment by hitesh-nitsan** [comment]
Hi @michelrossier @angeloprevitali 

Please find the option here > http://prntscr.com/cy956t

Thanks!

**Comment by michelrossier** [comment]
Thanks that works
