### ISSUE TITLE
Hardcoded sender mail: Mails that are sent out to users have "John Doe" as sender shown

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_memberlist#3]
Sender in mails is "John Doe" and similar e-mail address, netc_memberlist\Classes\Controller\UserController.php - Please make that this is not hardcoded, but that the sender information of the user who sends is applied instead.

**Comment by nitsan-technologies** [comment]
Hi @michelrossier 

Please check it now > http://prntscr.com/cdndy8

Thank you!

**Comment by michelrossier** [comment]
That works, thank you!
