### ISSUE TITLE
When bills are sent, the system doesn't chose the billing e-mail address

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_memberlist#30]
When the accounting user wants to send the bill by the message module, then it uses the default e-mail address (fieldname: email) and not the e-mail address defined in the billing section (bemail).

This is very important that when the accounting user wants to sell a bill, that this bill is sent to the billing address e-mail always.

**Comment by hitesh-nitsan** [comment]
Hi @michelrossier 

We have changed it. Please check it now. Thanks!

**Comment by michelrossier** [comment]
Hi 
Thanks for your work, that seems to work. But one question: When the regular users send a message with the message module, does it then take the billing address too or does this then go to the normal business e-mail address?

Only when the accountant user is sending a message it shall use the billing e-mail address, as described in the initial ticket. 

Thank you.

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

I am writing this update behalf of @hitesh-nitsan  as he is on sick leave. 

**Status** > Done
**Comment** > As per your last message we have adapted the functionality. So please review it. We changed this on Dev server and also uploaded on the Git.

Please share your feedback on this with us.

Regards.

**Comment by michelrossier** [comment]
Thanks, this works. Thanks for the fast fix, very appreciated.
