### ISSUE TITLE
When the user changes his profile in frontend it deletes all assigned groups except one

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_memberlist#31]
We figured by accident that there is a issue that causes data loss. When the frontend user changes some **data in his profile in the frontend**, the system **deletes all groups, but one** (the one that is visible in the frontend):

You can replicate this the following way:

![datalossexample](https://cloud.githubusercontent.com/assets/1160557/20486473/2ae146f6-b000-11e6-8d06-28d745a7f8e1.jpg)

Can you fix this? The website is already live and we currently disabled the group field, after we found out about this issue.

**Comment by hitesh-nitsan** [comment]
Hi @michelrossier 

Thanks for ticket.

It seems that you are trying to add usergroup from backend & frontend. Either you should do it by frontend OR backend.

**Problem:**  At backend, we are showing all usergroups with mutli select option. And at frontend, we have listed only few groups with single select option.

**Current issue:**  You have saved group with single select (frontend) So it removed other selected groups & save only one.

As of now, we have not any solution, you have restricted few group at frontend those will not listed if we allow multi select option at frontend. Can we remove this restriction & allow same select way as we did at backend?

Please guide us. Thanks!
