### ISSUE TITLE
Message module: All recipient e-mails together in "To:" field

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_memberlist#32]
Hi

We just sent the first official mail to the members and realizied, that all 300+ e-mails are placed in the "To:" field together. Meaning, all 300+ recipients see the e-mail address of the other 300 recipients. That is not good.

Can you change this that not all recipients are in the "To:" field, but each member gets 1 e-mail?

Best regards,
Michel

**Comment by hitesh-nitsan** [comment]
Hi @michelrossier 

Thank you for your message.

Yes, you are right. This is not good to send mail to all at once. We have changed it & uploaded to server.

GitHub Change log: https://github.com/NetConsultAG/netc_memberlist/commit/042509ac35af229ae8192ce215ebd42102405d3d#diff-2df765fd3b86889cdbf3841149671912

**Note: We are not able to test this change.**

Please check & let us know if any issue/problem there. Thanks!

**Comment by michelrossier** [comment]
Hi Hitesh

Thanks for the fast fix!

We tested this and it works in most cases. The problem ist, if a user sends 8MB attachment to several hundered recipients, this might cause a session timeout or other error.

We currently think it might be more scalable if we send the messages by adding the mails to BCC field and the TO: field to the sender (like the FROM field).

How do you see it, would that be a better solution? 

My issue currently is TIME. I am going to vacation tomorrow. Is it possible for you to find a solution today?

**Comment by hitesh-nitsan** [comment]
Hi @michelrossier 

As per our Skype discussion (yesterday), We have close this task. Please check & confirm. 

Thank you!

**Comment by michelrossier** [comment]
Everything okay, I close this, thank you.
