### ISSUE TITLE
User should not be able to send e-mail to category "Admin" or "Editor"

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_memberlist#4]
When a user wants to send a mail in the members area, then he shall not be able to send to "Admin" and "Editor". Please remove those 2 from the dropdown.

**Comment by nitsan-technologies** [comment]
Hi @michelrossier 

We have done this > http://prntscr.com/cdnkkt , http://prntscr.com/cdnkpu , http://prntscr.com/cdnktf

_Note: The functionality made for issue-5 will effect here also. restricted usergroups will not shown in dropdown in message module also._

Thank you!

**Comment by michelrossier** [comment]
That is almost okay. There is one problem though: The user shall not be able to chose a certain category in the register and edit form, but he shall be able to send a message to this certain category.

So this category has to be appearing in the dropdown of the message module but not on the other forms. It is about the category "	Alle SGRM Mitglieder" with the id 54, 

Do you have an idea how to solve that? Thanks.

**Comment by hitesh-nitsan** [comment]
Hi @michelrossier 

We have fixed that problem. Please check it now. Thanks!

**Comment by michelrossier** [comment]
That works, thank you.
