### ISSUE TITLE
On the page "My membership"  and "register" the user shall be restricted in choice of groups

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_memberlist#5]
On the page "My membership" and "Sign up" the user shall not be able to chose the groups "admin" and "editor", "Alle SGRM Mitglieder" and "Accounting usergroup" in any case. Please remove these groups from these pages.

**Comment by nitsan-technologies** [comment]
Hi @michelrossier 

Please check it now > http://prntscr.com/ce8xmj , http://prntscr.com/ce8xxp , http://prntscr.com/ce8xtl

_Note: You can now add restricted usergroups which will be affected in all places where usergroup selections._

Thank you!

**Comment by michelrossier** [comment]
That works, thank you.
