### ISSUE TITLE
On page "My Membership" if user doesn't chose "membership type" system error page is shown

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_memberlist#6]
If the "membership type" is not chosen on the "my membership" page and form is submitted, then there appears a T3 error page instead of just an error message. Please display error message instead and not the T3 system error page.

**Comment by nitsan-technologies** [comment]
Hi @michelrossier 

Please check it now > http://prntscr.com/ce8ylo , http://prntscr.com/ce90pe

Thank you!

**Comment by michelrossier** [comment]
That works, thank you.
