### ISSUE TITLE
After user registration, user is assigned to multiple groups that he didn't chose

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_memberlist#7]
After user registers, he is assigend to several groups, instead of just the one he chose in the form. For example we've chosen "Forensische Genetik", but the user then was assigned to additionally forensische Chemie und Toxikologie, Forensische Medizin and Verkehrsmedizin.

Please make sure that only the group is attached that the user has chosen during the registration process. **Plus additionally the group "Alle SGRM Mitglieder"**. All members shall have "Alle SGRM Mitglieder", so we have the option to send a mail to everyone.

So in the end if a user choses the group "Forensische Genetik" in his profile there has to be "Forensische Genetik" and "Alle SGRM Mitglieder" defined as groups.

**Comment by nitsan-technologies** [comment]
Hi @michelrossier 

We have done this > http://prntscr.com/ce97u3

_Note: You can add usergroup id in constant which will be preselected for user while he gets registered_

Thank you!

**Comment by michelrossier** [comment]
This worked, the defined group is attached after registration. But for some reason it does not apply the chosen usergroup field. 

For example:
http://sgrm.netconsult.ch/de/allgemein/mitgliedschaft/mitgliedschaft-beantragen/

Here the second dropdown field "Mitglied der Sektion" the user specifies in which usergroup he belongs to. But after the registration the user is not attached to this group only to the one that was preselected.

But the goal is: The user is applied to the preselected usergroup AND the one he is chosing in the form.

**Comment by hitesh-nitsan** [comment]
Hi @michelrossier 

Please check it now.

Registration- http://prntscr.com/cnbzp7 , http://prntscr.com/cnbzuk
Backend - http://prntscr.com/cnc0iu

Thanks!

**Comment by michelrossier** [comment]
This is okay, thanks!
