### ISSUE TITLE
In register form Birthdate format is wrong

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_memberlist#8]
- Birthdate format is wrong, please use the middle european variant: DD.MM.YYYY

**Comment by nitsan-technologies** [comment]
Hi @michelrossier 

Please check it now > http://prntscr.com/ce9hs7

Thank you!

**Comment by michelrossier** [comment]
Thanks, but this syntax is not correct:

`		value="{user.dateOfBirth -> f:format.date( format: 'dd.mm.yyyy' )}' )}"`

It renders the` )}'` in the form in the forntend.

**Comment by hitesh-nitsan** [comment]
Hi @michelrossier 

Please check it now > http://prntscr.com/cnb16v

Thanks!

**Comment by michelrossier** [comment]
This works, thank you.
