### ISSUE TITLE
Form validation is needed for more fields

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_memberlist#9]
Form validation for following fields is needed: 
http://web.archive.org/web/20160127154911/http:/www.sgrm.ch/allgemein/mitgliederbereich/24-neues-konto-eroeffnen.html

**Comment by nitsan-technologies** [comment]
Hi @michelrossier 

Please check it now >  http://prntscr.com/cdn2ig , http://prntscr.com/cdn2tf , http://prntscr.com/cdn2yd , http://prntscr.com/cdn30x

Thank you!

**Comment by michelrossier** [comment]
That works, thank you!
